server:
  port: 8084

spring:
  application:
    name: MybatisDynamicSourceProject
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.31.77:3306/db1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://192.168.31.77:3306/db2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver